### ISSUE TITLE
Cannot install  infernal-1.1.2-linux-intel-gcc on ubuntu 14.04

### ISSUE THREAD

**Issue by ashaneev** [EddyRivasLab/infernal#10]
Hiiii..
I am trying to install infernal-1.1.2-linux-intel-gcc on my system. But  after "make install"  i am getting the following error.
Please help me.

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/src$ make install
for file in cmalign cmbuild cmcalibrate cmconvert cmemit cmfetch cmpress cmscan cmsearch cmstat; do \
	   /usr/bin/install -c -m 0755 $file /usr/local/bin/ ;\
	done
/usr/bin/install: cannot stat ‘cmalign’: No such file or directory
/usr/bin/install: cannot stat ‘cmbuild’: No such file or directory
/usr/bin/install: cannot stat ‘cmcalibrate’: No such file or directory
/usr/bin/install: cannot stat ‘cmconvert’: No such file or directory
/usr/bin/install: cannot stat ‘cmemit’: No such file or directory
/usr/bin/install: cannot stat ‘cmfetch’: No such file or directory
/usr/bin/install: cannot stat ‘cmpress’: No such file or directory
/usr/bin/install: cannot stat ‘cmscan’: No such file or directory
/usr/bin/install: cannot stat ‘cmsearch’: No such file or directory
/usr/bin/install: cannot stat ‘cmstat’: No such file or directory
make: *** [install] Error 1

**Comment by nawrockie** [comment]
It looks like you've downloaded the source distribution with binaries. The binary executable files (e.g. cmalign) are in the infernal-1.1.2-linux-intell-gcc/binaries directory. You can copy these to /usr/local/bin or wherever you want to 'install' them. 

Copying the binaries/ is the easiest way, but if those binaries don't work for some reason, you can build your distribution from src, with: './configure; make; make install' if you go that route, the 'make install' step should work, but only because you did the previous './configure' and 'make' steps. If that still doesn't work, let me know.

**Comment by ashaneev** [comment]
Thank you.
 I've also tried the infernal-1.1.2 source file.but. after "make" it shows  the following error even within the /src folder.


veena@veena-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2$ cd src/
veena@veena-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2/src$ sudo make
     CC cmalign.o
     CC cm.o
     CC cm_alidisplay.o
     CC cm_alndata.o
     CC cm_dpalign.o
     CC cm_dpalign_trunc.o
     CC cm_dpsearch.o
     CC cm_dpsearch_trunc.o
     CC cm_dpsmall.o
     CC cm_file.o
     CC cm_modelconfig.o
     CC cm_modelmaker.o
     CC cm_mx.o
     CC cm_parsetree.o
     CC cm_pipeline.o
     CC cm_qdband.o
     CC cm_submodel.o
     CC cm_tophits.o
     CC cm_trunc.o
     CC cm_p7_band.o
     CC cm_p7_domaindef.o
     CC cm_p7_modelconfig_trunc.o
     CC cm_p7_modelmaker.o
     CC cp9.o
     CC cp9_dp.o
     CC cp9_modelmaker.o
     CC cp9_mx.o
     CC cp9_trace.o
     CC alphabet.o
     CC display.o
     CC errors.o
     CC eweight.o
     CC hmmband.o
     CC logsum.o
     CC mpisupport.o
     CC prior.o
     CC rnamat.o
     CC stats.o
     CC truncyk.o
     AR libinfernal-src.stamp
     SUBDIR impl_sse
make[1]: Entering directory `/home/veena/Documents/UN_GEnome/infernal-1.1.2/src/impl_sse'
     CC cm_optimized.o
     CC sse_cm_dpsearch.o
     CC sse_cm_dpsmall.o
     CC sse_cmcons_hitmx.o
     CC sse_cmcons_mscyk.o
     CC sse_util.o
     AR libinfernal-impl.stamp
make[1]: Leaving directory `/home/veena/Documents/UN_GEnome/infernal-1.1.2/src/impl_sse'
make: *** No rule to make target `../hmmer/src/libhmmer.a', needed by `cmalign'.  Stop.


That's why i chose the source with binary file. As you mentioned, i tried to copy the binaries to usr/local/bin.but,it omitted.

**Comment by nawrockie** [comment]
>As you mentioned, i tried to copy the binaries to usr/local/bin.but,it omitted.

I'm not sure what you meant by this. Did copying the binaries work for you? Or are you still having a problem.

**Comment by ashaneev** [comment]
No. I can't copy the binaries.
Thank you.

**Comment by nawrockie** [comment]
Please be more specific about why you can't copy the binaries. If there is an error, please send me the command that you tried and the output or error output of that command.

**Comment by ashaneev** [comment]
sorry for the inconvenience caused.
I did the following commands
        tar -xvzf  infernal-1.1.2.tar.gz
        cd infernal-1.1.2
        ./configure
        make

I've attached the output and output errors.

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2$ ./configure
configure: Configuring Infernal for your system.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
configure: Full Infernal source distribution - using full configuration
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for C compiler vendor... gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for cc_r... gcc
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for C compiler vendor... (cached) gnu
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking whether ln -s works... yes
checking whether you have a GNU make... yes, you do; and we assume you will use it!
./configure: line 5859: AX_CC_MAXOPT: command not found
checking for gcc -std=gnu99 option to produce PIC... -fPIC
checking whether C compiler accepts -msse2... yes
checking whether C compiler accepts -msse2 -msse3... yes
checking compiler support for sse2 cast functions... yes
checking whether SSE2 is supported... yes
checking whether _MM_SET_FLUSH_ZERO_MODE is supported... yes
configure: Activating Intel/AMD SSE optimized DP implementation
checking compiler support --start-group... yes
checking for gzip... /bin/gzip
checking for library containing clock_gettime... none required
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/types.h... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for sys/sysctl.h... yes
checking emmintrin.h usability... yes
checking emmintrin.h presence... yes
checking for emmintrin.h... yes
checking pmmintrin.h usability... no
checking pmmintrin.h presence... no
checking for pmmintrin.h... no
checking xmmintrin.h usability... yes
checking xmmintrin.h presence... yes
checking for xmmintrin.h... yes
checking whether byte ordering is bigendian... no
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for off_t... yes
checking for mkstemp... yes
checking for popen... yes
checking for strcasecmp... yes
checking for times... yes
checking for getpid... yes
checking for sysctl... yes
checking for sysconf... yes
checking for getcwd... yes
checking for stat... yes
checking for fstat... yes
checking for ntohs... yes
checking for ntohl... yes
checking for htons... yes
checking for htonl... yes
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
configure: creating ./config.status
config.status: creating src/Makefile
config.status: creating src/impl_sse/Makefile
config.status: creating testsuite/Makefile
config.status: creating rmark/Makefile
config.status: creating documentation/Makefile
config.status: creating documentation/manpages/Makefile
config.status: creating documentation/userguide/Makefile
config.status: creating hmmer/documentation/Makefile
config.status: creating hmmer/documentation/man/Makefile
config.status: creating hmmer/documentation/userguide/Makefile
config.status: creating hmmer/src/Makefile
config.status: creating hmmer/testsuite/Makefile
config.status: creating hmmer/profmark/Makefile
config.status: creating hmmer/src/impl_sse/Makefile
config.status: creating hmmer/libdivsufsort/Makefile
config.status: creating hmmer/Makefile
config.status: creating easel/miniapps/Makefile
config.status: creating easel/testsuite/Makefile
config.status: creating easel/Makefile
config.status: creating easel/documentation/Makefile
config.status: creating Makefile
config.status: creating src/config.h
config.status: creating hmmer/src/p7_config.h
config.status: creating hmmer/libdivsufsort/divsufsort.h
config.status: creating easel/esl_config.h
config.status: executing hmmer/src/impl commands


INFERNAL configuration:

     compiler:             gcc -std=gnu99 -g -O2 -msse2 -msse3 -pthread -fPIC
     linker:               
     libraries:              
     DP implementation:    sse

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2$ make
     SUBDIR easel
make[1]: Entering directory `/home/Documents/UN_GEnome/infernal-1.1.2/easel'
     CC easel.o
     CC esl_alphabet.o
     CC esl_avx.o
     CC esl_buffer.o
     CC esl_cluster.o
     CC esl_composition.o
     CC esl_dirichlet.o
     CC esl_distance.o
     CC esl_dmatrix.o
     CC esl_dsqdata.o
     CC esl_exponential.o
     CC esl_fileparser.o
     CC esl_gamma.o
     CC esl_gencode.o
     CC esl_getopts.o
     CC esl_gev.o
     CC esl_gumbel.o
     CC esl_heap.o
     CC esl_histogram.o
     CC esl_hmm.o
     CC esl_hyperexp.o
     CC esl_keyhash.o
     CC esl_mem.o
     CC esl_minimizer.o
     CC esl_mixgev.o
     CC esl_mpi.o
     CC esl_msa.o
     CC esl_msacluster.o
     CC esl_msafile.o
     CC esl_msafile2.o
     CC esl_msafile_a2m.o
     CC esl_msafile_afa.o
     CC esl_msafile_clustal.o
     CC esl_msafile_phylip.o
     CC esl_msafile_psiblast.o
     CC esl_msafile_selex.o
     CC esl_msafile_stockholm.o
     CC esl_msashuffle.o
     CC esl_msaweight.o
     CC esl_normal.o
     CC esl_paml.o
     CC esl_random.o
     CC esl_randomseq.o
     CC esl_ratematrix.o
     CC esl_recorder.o
     CC esl_regexp.o
     CC esl_rootfinder.o
     CC esl_scorematrix.o
     CC esl_sq.o
     CC esl_sqio.o
     CC esl_sqio_ascii.o
     CC esl_sqio_ncbi.o
     CC esl_sse.o
     CC esl_ssi.o
     CC esl_stack.o
     CC esl_stats.o
     CC esl_stopwatch.o
     CC esl_stretchexp.o
     CC esl_threads.o
     CC esl_tree.o
     CC esl_vectorops.o
     CC esl_vmx.o
     CC esl_weibull.o
     CC esl_workqueue.o
     CC esl_wuss.o
     AR libeasel.a
     SUBDIR miniapps
make[2]: Entering directory `/home/Documents/UN_GEnome/infernal-1.1.2/easel/miniapps'
     CC esl-afetch.o
     GEN esl-afetch
     CC esl-alimanip.o
In file included from /usr/local/include/assert.h:5:0,
                 from esl-alimanip.c:8:
/usr/local/include/except.h:5:44: fatal error: config.h: No such file or directory
 #include <config.h>  /* For HAVE_PTHREAD */
                                            ^
compilation terminated.
make[2]: *** [esl-alimanip.o] Error 1
make[2]: Leaving directory `/home/Documents/UN_GEnome/infernal-1.1.2/easel/miniapps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/Documents/UN_GEnome/infernal-1.1.2/easel'
make: *** [all] Error 2


when "make" command in the src folder

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2/src$ make
     CC cmalign.o
     CC cm.o
     CC cm_alidisplay.o
     CC cm_alndata.o
     CC cm_dpalign.o
     CC cm_dpalign_trunc.o
     CC cm_dpsearch.o
     CC cm_dpsearch_trunc.o
     CC cm_dpsmall.o
     CC cm_file.o
     CC cm_modelconfig.o
     CC cm_modelmaker.o
     CC cm_mx.o
     CC cm_parsetree.o
     CC cm_pipeline.o
     CC cm_qdband.o
     CC cm_submodel.o
     CC cm_tophits.o
     CC cm_trunc.o
     CC cm_p7_band.o
     CC cm_p7_domaindef.o
     CC cm_p7_modelconfig_trunc.o
     CC cm_p7_modelmaker.o
     CC cp9.o
     CC cp9_dp.o
     CC cp9_modelmaker.o
     CC cp9_mx.o
     CC cp9_trace.o
     CC alphabet.o
     CC display.o
     CC errors.o
     CC eweight.o
     CC hmmband.o
     CC logsum.o
     CC mpisupport.o
     CC prior.o
     CC rnamat.o
     CC stats.o
     CC truncyk.o
     AR libinfernal-src.stamp
     SUBDIR impl_sse
make[1]: Entering directory `/home/Documents/UN_GEnome/infernal-1.1.2/src/impl_sse'
     CC cm_optimized.o
     CC sse_cm_dpsearch.o
     CC sse_cm_dpsmall.o
     CC sse_cmcons_hitmx.o
     CC sse_cmcons_mscyk.o
     CC sse_util.o
     AR libinfernal-impl.stamp
make[1]: Leaving directory `/home/Documents/UN_GEnome/infernal-1.1.2/src/impl_sse'
make: *** No rule to make target `../hmmer/src/libhmmer.a', needed by `cmalign'.  Stop.

**Comment by nawrockie** [comment]
Thanks. And what happens when you try to copy and run the binaries in the binaries/ directory?

**Comment by ashaneev** [comment]
home@home-Lenovo-H30-50://usr/local/bin$ cp /home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/binaries .
cp: omitting directory ‘/home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/binaries’

**Comment by nawrockie** [comment]
That 'cp' command as you've written it won't work because /home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/binaries' is a directory. To copy the executable files only to the current dir, try this:

cp /home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/binaries/* .

Then try to run one of the binary files, like this:

./cmsearch -h

And let me know what the output is.

**Comment by ashaneev** [comment]
Thanks. It worked.But, still facing problem with "make" command.


home@home-Lenovo-H30-50://usr/local/bin$ sudo cp /home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/binaries/* .
[sudo] password for home: 
veena@veena-Lenovo-H30-50://usr/local/bin$


veena@veena-Lenovo-H30-50://usr/local/bin$ ./cmsearch -h
# cmsearch :: search CM(s) against a sequence database
# INFERNAL 1.1.2 (July 2016)
# Copyright (C) 2016 Howard Hughes Medical Institute.
# Freely distributed under a BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: cmsearch [options] <cmfile> <seqdb>

Basic options:
  -h        : show brief help on version and usage
  -g        : configure CM for glocal alignment [default: local]
  -Z <x>    : set search space size in *Mb* to <x> for E-value calculations  (x>0)
  --devhelp : show list of otherwise hidden developer/expert options

Options directing output:
  -o <f>       : direct output to file <f>, not stdout
  -A <f>       : save multiple alignment of all significant hits to file <s>
  --tblout <f> : save parseable table of hits to file <s>
  --acc        : prefer accessions over names in output
  --noali      : don't output alignments, so output is smaller
  --notextw    : unlimit ASCII text output line width
  --textw <n>  : set max width of ASCII text output lines  [120]  (n>=120)
  --verbose    : report extra information; mainly useful for debugging

Options controlling reporting thresholds:
  -E <x> : report sequences <= this E-value threshold in output  [10.0]  (x>0)
  -T <x> : report sequences >= this score threshold in output

Options controlling inclusion (significance) thresholds:
  --incE <x> : consider sequences <= this E-value threshold as significant  [0.01]
  --incT <x> : consider sequences >= this score threshold as significant

Options controlling model-specific reporting thresholds:
  --cut_ga : use CM's GA gathering cutoffs as reporting thresholds
  --cut_nc : use CM's NC noise cutoffs as reporting thresholds
  --cut_tc : use CM's TC trusted cutoffs as reporting thresholds

Options controlling acceleration heuristics*:
  --max      : turn all heuristic filters off (slow)
  --nohmm    : skip all HMM filter stages, use only CM (slow)
  --mid      : skip first two HMM filter stages (SSV & Vit)
  --default  : default: run search space size-dependent pipeline  [default]
  --rfam     : set heuristic filters at Rfam-level (fast)
  --hmmonly  : use HMM only, don't use a CM at all
  --FZ <x>   : set filters to defaults used for a search space of size <x> Mb
  --Fmid <x> : with --mid, set P-value threshold for HMM stages to <x>  [0.02]

Other options*:
  --notrunc     : do not allow truncated hits at sequence termini
  --anytrunc    : allow full and truncated hits anywhere within sequences
  --nonull3     : turn off the NULL3 post hoc additional null model
  --mxsize <x>  : set max allowed alnment mx size to <x> Mb [df: autodetermined]
  --smxsize <x> : set max allowed size of search DP matrices to <x> Mb  [128.]
  --cyk         : use scanning CM CYK algorithm, not Inside in final stage
  --acyk        : align hits with CYK, not optimal accuracy
  --wcx <x>     : set W (expected max hit len) as <x> * cm->clen (model len)
  --toponly     : only search the top strand
  --bottomonly  : only search the bottom strand
  --tformat <s> : assert target <seqdb> is in format <s>: no autodetection
  --cpu <n>     : number of parallel CPU workers to use for multithreads

*Use --devhelp to show additional expert options.

	

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc$ sudo make
     SUBDIR easel
make[1]: Entering directory `/home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/easel'
     SUBDIR miniapps
make[2]: Entering directory `/home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/easel/miniapps'
     CC esl-alimanip.o
In file included from /usr/local/include/assert.h:5:0,
                 from esl-alimanip.c:8:
/usr/local/include/except.h:5:44: fatal error: config.h: No such file or directory
 #include <config.h>  /* For HAVE_PTHREAD */
                                            ^
compilation terminated.
make[2]: *** [esl-alimanip.o] Error 1
make[2]: Leaving directory `/home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/easel/miniapps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/Documents/UN_GEnome/infernal-1.1.2-linux-intel-gcc/easel'
make: *** [all] Error 2

**Comment by nawrockie** [comment]
Glad that worked. I'm not sure why 'make' fails for you, and I don't have access to an Ubuntu 14.04 machine to check. However, you shouldn't need it, now that you have the binaries, there's no reason for you to need 'make' to work. The whole point of 'make' is to generate the binaries. I suggest you use the premade binary executables and forget about 'make'.

**Comment by ashaneev** [comment]
Thank You so much. But, still i have few more doubts. Is there any need of "make install" ?
I've tried with sudo make install but, i got error messages. How the infernal would work without successful installation ? I've copied the binaries to bin but, " ./cmsearch -h"  command only work in /bin and /binaries. Why i couldn't  run within the infernal folder ? is it possible? 
Your consideration will be a sort of great favor.

**Comment by nawrockie** [comment]
The critical step of 'make install' is to copy the binary files (all the files in the binaries/ directory) to a system-wide directory that is in your PATH. By default this is: /usr/local/bin/. You can either copy the binaries there, or to some other directory that is in your PATH or you can modify your PATH to include the binaries/ directory or whatever directory you put the binaries/ in. Once the binaries are in a directory in your PATH then you can execute them from any directory with a command like 'cmsearch -h'.

Here is a website that explains what your PATH is in Unix:
https://kb.iu.edu/d/acar
There are many other similar websites that you can find using google.

**Comment by ashaneev** [comment]
Thank you so much. It worked.
