### ISSUE TITLE
annotating a large assembly/scaffolds

### ISSUE THREAD

**Issue by dcopetti** [EddyRivasLab/infernal#13]
Hello,
What is the best way to annotate a large genome assembly? 
My assembly is 4.5 Gb in total, with a scaffold N50 of 3 Mb (80% of the sequence is in scf >1 Mb). 
After reading here http://rfam.readthedocs.io/en/latest/genome-annotation.html, I thought of splitting the assembly in 20 chunks, but still I would need almost 500 GB of RAM.
Besides splitting in smaller files, is there a way to run it efficiently (also, controlling the number of cpus that it takes on a local server)?
With smaller genomes, my command is 
`cmscan -Z 59.752452 --cut_ga --rfam --nohmmonly --tblout genome12_infernal --fmt 1 --clanin Rfam12.2.claninfo Rfam.desc.cm genome12.fasta > genome12.cmscan`
thanks,

Dario

**Comment by nawrockie** [comment]
Hi Dario,

The instructions you referred to on rfam.readthedocs are still current, and I recommend you just follow those. 

Splitting the genome into 20 chunks is fine and makes sense if you're able to run 20 cmscan jobs in parallel, otherwise you may just want to leave the assembly as one file. It will not require 500 Gb of RAM (I'm not sure how you got this), but rather 1-4 Gb per thread. You can control the number of threads with --cpu <n> to specify <n> threads.

If you do split into chunks, make sure you calculate the -Z argument correctly (see #4 on the readthedocs page). This argument should be the total number of Mb in the full assembly, counting each strand separately, so something like -Z 9000 is correct for a 4.5 Gb assembly.

Eric

**Comment by dcopetti** [comment]
Thank you for the quick feedback!
I must have got confused with the zeros...

So now I run a test as 
```
infernal_annotation_files]$ cmscan -Z 10000 --cpu 2 --cut_ga --rfam --nohmmonly --tblout Rfam_00_infernal --clanin /home/copettid/bin/infernal-1.1.2/testsuite/Rfam.12.1.clanin --fmt 2 --oskip --oclan Rfam.cm Rabiosa_genome_1.0_00.fasta >Rfam_00.cmscan

Error: unable to find model RyeB listed in /home/copettid/bin/infernal-1.1.2/testsuite/Rfam.12.1.clanin in SSI index file
[copettid@kp141-242 infernal_annotation_files]$ grep RyeB /home/copettid/bin/infernal-1.1.2/testsuite/Rfam.12.1.clanin
CL00105 SraC_RyeA RyeB
```
I see the line in the clanin file, then I don't understand what the error really says. Permissions in that folder? 
```
ls -la /home/copettid/bin/infernal-1.1.2/
total 1580
drwxr-xr-x 11 copettid mpb   4096 Jun 25 15:02 .
drwxr-xr-x 29 copettid mpb   4096 Jun 25 15:02 ..
-rw-r--r--  1 copettid mpb  32455 Jul  1  2016 aclocal.m4
-rw-r--r--  1 copettid mpb  44914 Jul  1  2016 config.guess
-rw-r--r--  1 copettid mpb  50071 Jun 25 15:02 config.log
-rwxr-xr-x  1 copettid mpb  33340 Jun 25 15:02 config.status
-rw-r--r--  1 copettid mpb  33774 Jul  1  2016 config.sub
-rwxr-xr-x  1 copettid mpb 355498 Jul  1  2016 configure
-rw-r--r--  1 copettid mpb  27227 Jul  1  2016 configure.ac
drwx------  2 copettid mpb   4096 Jun 25 15:02 confv3gsdL
drwxr-xr-x  4 copettid mpb   4096 Jun 25 15:02 documentation
drwxr-xr-x  9 copettid mpb  12288 Jun 25 15:05 easel
drwxr-xr-x  8 copettid mpb   4096 Jun 25 15:06 hmmer
-rw-r--r--  1 copettid mpb   2362 Jul  1  2016 INSTALL
-rw-r--r--  1 copettid mpb   8316 Jul  1  2016 install-sh
-rw-r--r--  1 copettid mpb   2755 Jul  1  2016 LICENSE
-rw-r--r--  1 copettid mpb   8272 Jun 25 15:02 Makefile
-rw-r--r--  1 copettid mpb   8319 Jul  1  2016 Makefile.in
drwxr-xr-x  2 copettid mpb  12288 Jul  1  2016 matrices
-rw-r--r--  1 copettid mpb   1426 Jul  1  2016 README
-rw-r--r--  1 copettid mpb   1254 Jul  1  2016 RELEASE-NOTES
drwxr-xr-x  2 copettid mpb   4096 Jun 25 15:04 rmark
drwxr-xr-x  3 copettid mpb   4096 Jun 25 15:05 src
drwxr-xr-x  2 copettid mpb  12288 Jun 25 15:08 testsuite
drwxr-xr-x  3 copettid mpb   4096 Jul  1  2016 tutorial
-rw-r--r--  1 copettid mpb 905189 Jul  1  2016 Userguide.pdf
```
or do I need to process the clanin file first?
Thanks,

Dario

**Comment by nawrockie** [comment]
I think the .clanin file you're using is not the correct one. It must correspond to Rfam.cm. You should download both from the Rfam ftp site. See step 2 on the readthedocs page.

**Comment by dcopetti** [comment]
yep,
I had different versions - thanks for pointing it out.
Dario
