### ISSUE TITLE
make install error 1

### ISSUE THREAD

**Issue by NikkiCase** [EddyRivasLab/infernal#22]
Hi! I am trying to download infernal and am getting the following error during installation. 

mh_user@MicrobiomeHelper:~/metatranscriptomics/infernal-1.1.3$ make install
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -d /usr/local/share/doc/infernal
/usr/bin/install: cannot change permissions of ‘/usr/local/share/doc/infernal’: No such file or directory
Makefile:155: recipe for target 'install' failed
make: *** [install] Error 1

Thank you for your help!

Nikki

**Comment by npcarter** [comment]
Hello.  Are you running "make install" without using sudo or logging in as 
root?  A normal user will typically not have permission to make changes in 
/use/local/share, and will generate errors like the ones you're seeing.

**Comment by NikkiCase** [comment]
Great advice!! I am new to coding and had never heard of sudo. That fixed it. Thank you!

**Comment by npcarter** [comment]
Great! Glad to be of help.

-Nick
