### ISSUE TITLE
how to get the ./configure file

### ISSUE THREAD

**Issue by li0604** [EddyRivasLab/infernal#24]
Dear professor，
I will install this software,but I can find the ./configure file. I have tried the commond ” autoconf ”.It doesn't work. Would you mind give me a help for installing this software?
The error showing as follow:
./configure --prefix /backup/liqm/software/infernal-master
-bash: ./configure: 没有那个文件或目录

autoconf 
/usr/bin/m4:configure.ac:60: cannot open `easel/m4/ax_check_gnu_make.m4': No such file or directory
/usr/bin/m4:configure.ac:62: cannot open `easel/m4/ax_compiler_vendor.m4': No such file or directory
/usr/bin/m4:configure.ac:63: cannot open `easel/m4/ax_check_compile_flag.m4': No such file or directory
/usr/bin/m4:configure.ac:64: cannot open `easel/m4/ax_gcc_func_attribute.m4': No such file or directory
/usr/bin/m4:configure.ac:66: cannot open `easel/m4/esl_sse.m4': No such file or directory
/usr/bin/m4:configure.ac:67: cannot open `easel/m4/esl_vmx.m4': No such file or directory
/usr/bin/m4:configure.ac:69: cannot open `easel/m4/ax_prog_cc_mpi.m4': No such file or directory
/usr/bin/m4:configure.ac:70: cannot open `easel/m4/ax_pthread.m4': No such file or directory
/usr/bin/m4:configure.ac:72: cannot open `easel/m4/esl_pic_flags.m4': No such file or directory

Thanks a lot.

**Comment by nawrockie** [comment]
I'm guessing you resolved the issue because you closed it, but if you are looking to install the latest stable release (1.1.4), follow the instructions in the INSTALL file here:
https://github.com/EddyRivasLab/infernal/blob/master/INSTALL

If you want to clone the git repo and do development, see this:
https://github.com/EddyRivasLab/infernal/wiki

Let me know if you have questions

**Comment by li0604** [comment]
Thank you very much.
It works when I install " http://eddylab.org/infernal/infernal-1.1.4-linux-intel-gcc.tar.gz" .
It's really kind of you.


Qingmei. 

















在 2020-12-17 21:30:05，"Eric Nawrocki" <notifications@github.com> 写道：

I'm guessing you resolved the issue because you closed it, but if you are looking to install the latest stable release (1.1.4), follow the instructions in the INSTALL file here:
https://github.com/EddyRivasLab/infernal/blob/master/INSTALL

If you want to clone the git repo and do development, see this:
https://github.com/EddyRivasLab/infernal/wiki

Let me know if you have questions
