### ISSUE TITLE
Error: removing/marking overlapping hits, stop posn is inconsistent, hit 33085 during cmsearch run

### ISSUE THREAD

**Issue by jaswindersingh2** [EddyRivasLab/infernal#28]
Hi,

I was searching a covariance model against NCBI's database using `cmsearch` from `infernal-1.1.4-linux-intel-gcc` package and got the following error:

``
Error: removing/marking overlapping hits, stop posn is inconsistent, hit 33085
``

Any response would be greatly appreciated.

Thank you!

**Comment by nawrockie** [comment]
@jaswindersingh2 : can you please provide the CM and fasta file along with the specific command you used so that I can reproduce the error and look into it?

**Comment by jaswindersingh2** [comment]
Thank you for the quick response.

I think, I have figured out the issue. There were few duplicates in the reference database which results in above error. Once I removed duplicates from reference database, it works perfectly fine.

Thank you!

**Comment by nawrockie** [comment]
@jaswindersingh2  I'm glad that you were able to find a workaround. Do you mind sending me the files to reproduce anyway? It looks like a bug and I'd like to fix it. If you'd rather not post to github but are okay with sending to me directly, you can email me at eric.nawrocki@nih.gov. Or explaining exactly how you created your CM database and fasta file would work too.  Thanks.
