### ISSUE TITLE
Conda version 1.1.4 but -h shows 1.1.3

### ISSUE THREAD

**Issue by ramanujamr** [EddyRivasLab/infernal#32]
Hello

I tried installing infernal through conda
`conda install -c bioconda -c conda-forge infernal`

![Screenshot 2022-12-28 at 10 36 30 AM](https://user-images.githubusercontent.com/98770233/209844098-eace913d-f8a2-41ec-a9f8-a4abc7d18f2b.png)

The installed conda version shows 1.1.4, but the `cmscan -h` command shows the version as 1.1.3

![Screenshot 2022-12-28 at 10 39 12 AM](https://user-images.githubusercontent.com/98770233/209844359-a3c53765-c679-4555-8b6d-f6b558538345.png)

This is creating issues in other tools which use cmscan when the version is checked.

Any ideas on what might be going on?

-Ram

**Comment by npcarter** [comment]
Have you checked to make sure there isn’t another version of Infernal
somewhere on your system?  “which infernal” will return the complete file
name of the first Infernal executable in your path.  If that finds a
version of Infernal that isn’t the Conda version, you can either remove it
or chance the order of directories in your PATH environment variable so
that the Conda version of Infernal appears before the other one.

**Comment by ramanujamr** [comment]
@npcarter 
There doesn't seem to be another version of infernal that's conflicting.
Using `which cmscan` gets me this:
`/home/[USERNAME]/miniconda3/envs/infernal/bin/cmscan`

I installed this in a new Conda environment called "infernal" without any other packages.
I also checked my PATH variables.

**Comment by ramanujamr** [comment]
It magically seems to be fixed now.
I just logged out of the remote server and logged back in.
I have no idea what changed. Looks like this is going to be another unsolved mystery...

Thanks for your help @npcarter

**Comment by npcarter** [comment]
Huh, that's weird.  Glad to know it's working!

-Nick
