### ISSUE TITLE
cmbuild with fragmentary sequences, terminal self-inserts can lead to problematically high self-insert probabilities

### ISSUE THREAD

**Issue by nawrockie** [EddyRivasLab/infernal#34]
For `cmbuild` to more appropriately handle missing data from fragmentary sequences (being implemented in the `buildfrags` feature branch), truncated parsetrees are allowed, but in rare cases if a parsetree ends with self inserts (IL->IL or IR->IR) it may lead to the corresponding self-insert probability that is problematically high. If the only transitions for an insert state implied by the alignment are self inserts, then all other transition counts will be 0, and the self insert can be very close to 1.0. This can be a problem in the QDB calculation engine, which is a step performed by `cmbuild` to determine the model's `W` parameter. If `W` grows larger than 1000 times the model length (`clen`) `cmbuild` fails with an error as this was thought to be an indication that something was wrong. This is undesirable for the impact on W and the expected length distribution from the offending insert, so instead of increasing the `1000*clen` threshold, I want to modify the parsetree somehow to avoid such a high self-insert probability in these cases.

**Comment by ppgardne** [comment]
Sounds bloody tricky! Good luck.

**Comment by nawrockie** [comment]
Fixed as of commit cbb2153 on `build-frags` feature branch. This will likely go into `develop` soon but if `build-frags` is abandoned for some unforeseen issue, then it will not.

Strategy used to avoid the high self insert probabilities is to identify any truncated parsetrees in which the final transition (between the final two parsetree nodes) is a self insert transition in `cm_parsetree.c:ParsetreeCountExceptTruncatedMPs()` and add an extra count from that insert to the first state (`MATP_MP, MATL_ML, MATR_MR, BEGL_S, BEGR_S, or END_E`) of the following node, even though this is not implied by the alignment of the truncated sequence. This has the effect of lowering the resulting self insert transition probability sufficiently to avoid the problem. Note that any truncation for which the parsetree ends with a single insertion (that does not self transit) is not impacted.
