### ISSUE TITLE
cmalign core dump

### ISSUE THREAD

**Issue by bernt-matthias** [EddyRivasLab/infernal#35]
Dear infernal team. I try to build new CM for mitochondrial 16S. The following command line gives me a core dump:

```
cmalign --verbose -g --notrunc --cpu 0 --mxsize 65536 --sfile rrnL-bact.score -o rrnL-bact-org.stk --mapali LSU_rRNA_bacteria-RF02541.clean.stk LSU_rRNA_bacteria-RF02541.clean.cm rrnLtmp.fas
```

I tried with (`--cpu 8, 16, 32`) and without mutithreading (`--cpu 0`), played around with various `-mxsize` settings and I'm also pretty sure that the problem is not a lack of RAM (I have >1TB available and `cmalign` seemed to be quite a bit away from this .. depending on the number of cores I have seen up to ~300GB in the htop output). I'm using the 1.1.4 bioconda package, but also tried a local build.

I deposited the input data over here https://nc.ufz.de/s/tWsyE7dZg58LBaB  (password is `:v;{I8Ozl1`)

Would be grateful for any suggestions or help of any sort.

**Comment by nawrockie** [comment]
I'm looking into it. I'll get back to you when I know more.

**Comment by nawrockie** [comment]
@bernt-matthias : I've found that there are 6 sequences that cause problems in your dataset. If you remove these 6, you should be able to successfully complete your cmalign command.

NC_057071_1_26831_27511
NC_050844_1_2759_7293
NC_050846_1_24731_29145
NC_057071_1_97160_98398
NC_050838_1_50831_56837
NC_050342_1_33788_39285

One suggestion if you really want to include these 6 sequences is to run cmsearch on them to determine what regions match well to the model and only try to align those regions.

FYI, you can use the esl-alimerge program installed in infernal/easel/miniapps/ to combine alignments that were created with cmalign and the same CM file.

I'll continue to investigate these 6 sequences.

**Comment by bernt-matthias** [comment]
Thanks a lot for the update. May I ask how you identified the culprits? 

> One suggestion if you really want to include these 6 sequences is to run cmsearch on them to determine what regions match well to the model and only try to align those regions.

I was explicitly not doing this. I try to "extend" an existing model using annotated sequences. By allowing extensions that do not align to the original model I was hoping to allow for new extensions. Clearly the model constructed this way would not contain structure info, but still the sequence would be contained. 

> FYI, you can use the esl-alimerge program installed in infernal/easel/miniapps/ to combine alignments that were created with cmalign and the same CM file.

So I could replace the `--mapali` part by an extra program call and also include possible the alignment of the 6 sequences once they can be constructed in the future?

> I'll continue to investigate these 6 sequences.

Thank you so much!

**Comment by nawrockie** [comment]
>Thanks a lot for the update. May I ask how you identified the culprits?

I split your fasta file into many smaller files and ran cmalign on each separately. This eventually led me to seeing failures on 6 separate cmalign calls, one for each of these 6 sequences.

>I was explicitly not doing this. I try to "extend" an existing model using annotated sequences. By allowing extensions that do not align to the original model I was hoping to allow for new extensions. Clearly the model constructed this way would not contain structure info, but still the sequence would be contained.

Ok, I think I understand your strategy. In this particular case, due to this issue, you could just omit these 6 sequences, and try to build a new extended model from the others, then use that new model to try and align the 6 sequences. That may work.

>So I could replace the --mapali part by an extra program call and also include possible the alignment of the 6 sequences once they can be constructed in the future?

For the `--mapali part` it actually won't work that way with the .stk alignment you are using now. That is because `esl-alimerge` keys off the RF annotation in the alignment to perform the merge. However, if you rerun your `cmbuild` command and use the `-O <outstk>` (uppercase -O) option to resave the alignment with RF annotation, you can then use `<outstk>` with `--mapali` the way you are describing. 

As for adding in the 6 additional sequences in the future - yes, any two (or more) alignments created to the same CM are merge-able with `esl-alimerge`.

**Comment by bernt-matthias** [comment]
Little follow up. I had another core dump on the remaining species. Based on your approach I split my fasta in single sequences, ran `cmaling` on them and excluded all species where a core dump was observed. For the remaining species I was able to compute the complete alignment. So far this worked for all my data sets :) 

Thanks for the support and this nice piece of software.

**Comment by nawrockie** [comment]
@bernt-matthias Thanks for reporting this problem. I believe I have finally tracked this down. The fix involves changes in both infernal and the easel library. All the changes were related to 32-bit integer overflows in calculations related to very large dynamic programming matrices, and switching the relevant variables from type `int` to `int64_t` fixed the problem. 

If you really want to build a version of infernal that can successfully complete your original cmalign command, you can follow the instructions here: 

https://github.com/EddyRivasLab/infernal/blob/master/README.md#to-clone-a-copy-of-infernal-source-from-github

but in addition, after each of the `git clone` commands, execute `git checkout develop` to switch to the `develop` branches of infernal, hmmer and easel before building.
