### ISSUE TITLE
does cmsearch result return a single model found per target sequence

### ISSUE THREAD

**Issue by jflucier** [EddyRivasLab/infernal#41]
Hello,

I am running cmsearch using some RFAM models. I have read documentation but want to make sure I get this right before going further.

When I use cmsearch, will it try to find all occurences model in target sequence or just the best hit?

How would you proceed to find all occurences of model in a single target sequence? Using cmscan? Based on documentation, it is not clear for me. 

Thank you very much for your help,
JF

**Comment by cryptogenomicon** [comment]
cmsearch finds all hits in the target sequence, not just the best one.

See the tutorial in the user guide, at "Step 3: search a sequence database with cmsearch" and the example output there, for more information.

**Comment by jflucier** [comment]
thanks for quick response. Cannot believe I missed that. This part of userguide got me to doubt:

cmsearch is used to search one or more covariance models (CMs) against a sequence database. For each CM in
<cmfile>, use that query CM to search the target database of sequences in <seqdb>, and **output ranked lists of the
sequences with the most significant matches to the CM.**

thanks alot

**Comment by cryptogenomicon** [comment]
Thanks. I've changed that language in the cmsearch man page from "lists of sequences" to "lists of sequence regions", in our development branch. The change will appear in the next release.
