### ISSUE TITLE
readme and packages, containers

### ISSUE THREAD

**Issue by bgruening** [EddyRivasLab/infernal#6]
I would love to add the Bioconda packages, the BioContainer and the Galaxy wrapper to the readme, but it looks like it is autogenerated. Any idea where to add it.

https://anaconda.org/bioconda/infernal
https://quay.io/repository/biocontainers/infernal?tab=tags
https://toolshed.g2.bx.psu.edu/view/bgruening/infernal/

**Comment by cryptogenomicon** [comment]
I'm sorry, I don't understand what you want to do. Can you explain more?

Our README is only about Infernal itself; we don't have any links to other software packages there.

**Comment by bgruening** [comment]
You readme file is not a proper github markdown file: https://github.com/EddyRivasLab/infernal/blob/master/README

It looks wired in github and I think it is just more internally, because it also contains variables as well.
I wanted to add links to `infernal` packages for the conda package manager, for Docker containers and Galaxy integration. All of them are `infernal` integrations and things that makes it more easy to distribute and deploy infernal so I thought it would be nice to let the community now by putting the links somewhere prominent - maybe a readme file :)

**Comment by cryptogenomicon** [comment]
Thanks, but the README for Infernal doesn't seem like the right place for these links.

**Comment by bgruening** [comment]
And where is the correct place? These links will help the infernal community.

**Comment by cryptogenomicon** [comment]
I'll think about it, and discuss with Eric.

**Comment by cryptogenomicon** [comment]
I added these links to the [Infernal home page](http://eddylab.org/infernal). Thank you!

**Comment by bgruening** [comment]
Thanks @cryptogenomicon!

**Comment by cryptogenomicon** [comment]
btw, note that Infernal is now BSD licensed; the bioconda package has a GPLv3 flag on it.

**Comment by bgruening** [comment]
Oh sorry, I will fix this in https://github.com/bioconda/bioconda-recipes/pull/3484
