### ISSUE TITLE
Compiling the Entire Source

### ISSUE THREAD

**Issue by pramodcj** [EddyRivasLab/infernal#7]
Hi,
I want to make some changes in cmsearch, how could i compile the program as it is giving many errors.
what are the settings for compilation.

Thanks in advance.

**Comment by nawrockie** [comment]
I recommend downloading the v1.1.2 source distribution from http://eddylab.org/infernal/ and following the instructions for installation in the User's Guide Installation section. Let me know if you have problems/questions.
