### ISSUE TITLE
while running cmscan i am getting this error 

### ISSUE THREAD

**Issue by deepaksen1996** [EddyRivasLab/infernal#8]
Can you please suggest me changes in code 

roor4@roor4-HP-Compaq-Elite-8300-MT:~/infernal-1.1.2$ cmscan -Z 5.874406 --cut_ga --rfam --nohmmonly --tblout mrum-genome.tblout --fmt 2 --clanin Rfam12.2.claninfo Rfam.cm mrum-genome.fa mrum-genome.cmscan
Failed to parse command line: No such option "--fmt".
Usage: cmscan [-options] <cmdb> <seqfile>

where basic options are:
  -h        : show brief help on version and usage
  -g        : configure CM for glocal alignment [default: local]
  -Z <x>    : set search space size in *Mb* to <x> for E-value calculations  (x>0)
  --devhelp : show list of otherwise hidden developer/expert options

To see more help on available options, do /usr/lib/infernal/cmscan -h

**Comment by cryptogenomicon** [comment]
I'm not sure what you're trying to do. There's no option "--fmt" for cmscan. Do 'cmscan -h' and you'll see the complete list of options. Try removing "--fmt 2 mrumgenome.tblout" from your command, and that should work.

**Comment by deepaksen1996** [comment]
Sir, but I'm following this site and the code is given there and error is also 

roor4@roor4-HP-Compaq-Elite-8300-MT:~/infernal-1.1.2$ cmscan -Z 5.874406 --cut_ga --rfam --nohmmonly --tblout mrum-genome.tblout --fmt 2 --clanin Rfam12.2.claninfo Rfam.cm tutorial/mrum-genome.fa mrum-genome.cmscan

Failed to parse command line: No such option "--fmt".
Usage: cmscan [-options] <cmdb> <seqfile>


where basic options are:
  -h        : show brief help on version and usage
  -g        : configure CM for glocal alignment [default: local]
  -Z <x>    : set search space size in *Mb* to <x> for E-value calculations  (x>0)
  --devhelp : show list of otherwise hidden developer/expert options

To see more help on available options, do /usr/lib/infernal/cmscan -h

**Comment by deepaksen1996** [comment]
![screenshot from 2017-05-22 16-40-56](https://cloud.githubusercontent.com/assets/28804724/26305499/2899ab4e-3f0d-11e7-824b-4ddffd26afd7.png)

here is the "cmscan.c" file screenshot.

**Comment by cryptogenomicon** [comment]
Apologies, --fmt is a new option in 1.1.2. (I was checking in 1.1.1, which is what I have installed on my laptop right now.)

Make sure you're running 1.1.2. (Do `cmscan -h`.)  You may have an older Infernal in your $PATH. 1.1.1 does not have a --fmt option.

**Comment by deepaksen1996** [comment]
Sir
please run new infernal-1.1.2 suggest any changes because it is giving the same error about
--fmt
thanks for your previous replies.

**Comment by cryptogenomicon** [comment]
Works fine for me. Show me the output of `cmscan -h`, please.

**Comment by deepaksen1996** [comment]
![screenshot from 2017-05-22 19-04-10](https://cloud.githubusercontent.com/assets/28804724/26311242/343d2d04-3f21-11e7-8fcc-bccac1950285.png)

**Comment by cryptogenomicon** [comment]
You truncated the top of the output. I need to see the top of the output of `cmscan -h`, please.

**Comment by deepaksen1996** [comment]
sir now it is working thanks a lot for your help :+1:
